#!/usr/bin/env bash
basedir="$(dirname ${0})"
cd "${basedir}"
git pull > /dev/null
curl -s https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/maven.rb | sed 's/class Maven < Formula/class MavenNoopenjdk < Formula/g; s/depends_on \"openjdk\"//g' | sed -e '1h;2,$H;$!d;g' -re 's/bottle do.*end/bottle :unneeded/g' > Formula/maven-noopenjdk.rb
git add . && git commit -m "updated maven.rb from homebrew-core/master/Formula/maven.rb" > /dev/null && git push
